# Generated by Django 5.1 on 2024-08-25 14:48

import communication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('item', '0007_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={},
        ),
        migrations.RemoveField(
            model_name='communication',
            name='members',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(default=communication.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='subject',
            field=models.CharField(default='No subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
