# Generated by Django 5.1 on 2024-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_communication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(default='No subject', max_length=255, null=True),
        ),
    ]
