# Generated by Django 5.1 on 2024-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_slug_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
